vscode:
    extensions:
        - redhat.java
        - vscjava.vscode-java-debug
        - vscjava.vscode-java-test
        - vscjava.vscode-java-dependency
        - vscjava.vscode-maven
        - jebbs.plantuml
        - hediet.vscode-drawio
